### ISSUE TITLE
how to control significant digits on escape scores shown on tree?

### ISSUE THREAD

**Issue by jbloom** [blab/ncov-escape#3]
Right now the escape scores for the nodes when moused over are shown with many significant digits. How do I make these just one or two digits after the decimal? Round the numbers in JSON or some other method?

**Comment by trvrb** [comment]
You'll want to round scores when exporting the JSON. If the JSON has two significant digits then Auspice will display just two digits.

**Comment by jbloom** [comment]
Fixed in a1648a5e.
