### ISSUE TITLE
how to actual make live display of tree?

### ISSUE THREAD

**Issue by jbloom** [blab/ncov-escape#4]
I can visualize the tree with the escape scores locally with `auspice`. What is the process for hosting it so it is visualizable on the web?

**Comment by trvrb** [comment]
I've pushed to https://nextstrain.org/groups/blab/ncov/escape using
```
nextstrain remote upload nextstrain.org/groups/blab auspice/ncov_escape*.json
```
I've updated readme with this instruction in 924a5277b12543ee942d55682f895bb6fdee05bd.

@jbloom: For this to work for you, you'd need to be a member of the `blab` Nextstrain group. I'd think to just push live from blab accounts for the moment.

Alternatively, you could share through GitHub or through a Bloom Lab Groups account (if you wanted to maintain). Details on sharing analyses are here: https://docs.nextstrain.org/en/latest/guides/share/index.html

**Comment by jbloom** [comment]
@trvrb, this looks great, and I'm happy to just have you push updates as long as you don't mind me bugging you about it when it's needed.

Also, what is the process for updating to newer sequences as the weeks go by? I don't understand how sequences are obtained from GISAID well enough to know how this is done? Is this something where I'd just remind you every few weeks to re-run pipeline and push updated tree, or is there some more automated way?
