### ISSUE TITLE
make choice of BA.2 "reference" at root more robust

### ISSUE THREAD

**Issue by jbloom** [blab/ncov-escape#5]
Right now the spike for the reference is hardcoded into the script Trevor generated (https://github.com/blab/ncov-escape/commit/81e43a2b50b85b55d0b29f3e60380e3eaf54ce7e#diff-54f0382e7ad5485edc0f8936ebc650ad9a30d03bd39bcd4e0b1080800bf757afR15-R17), which doesn't seem ideal. How do we make this better and read from data?

**Comment by trvrb** [comment]
Right now, we're using SouthAfrica/NHLS-UCT-LA-Z957/2022 as basal BA.2. This manifests in multiple locations:

Data files:
- `data/ba2_outgroup_metadata.tsv`
- `data/ba2_outgroup_sequences/fasta`

```
refine:
  root: "SouthAfrica/NHLS-UCT-LA-Z957/2022"
```
in `escape_profiles/escape/builds.yaml`

`reference` is set in `escape_profiles/escape/sequence_to_escape.py`. I grabbed this from the workflow artifact `results/escape/translations/aligned.gene.S.fasta`

**Comment by trvrb** [comment]
I'm actually not very worried about having to have multiple places where this shows up. However, it would be good to make sure that this is a properly basal BA.2 virus.

**Comment by jbloom** [comment]
Sounds good. Is there a recommended way to determine what is a good basal BA.2 virus?

**Comment by trvrb** [comment]
Closing this issue as outdated.
