### ISSUE TITLE
frequencies plot looks wrong

### ISSUE THREAD

**Issue by jbloom** [blab/ncov-escape#7]
The frequencies plot on the live hosted page looks wrong: most earlier sequences are unassigned. See image below:
![Screen Shot 2022-08-16 at 2 56 52 PM](https://user-images.githubusercontent.com/1906801/184992511-961cfb0b-7389-4699-8755-6ca1d3cae5ab.png)

 I'm not sure why this is? Is it because internal nodes don't have an escape score?

Maybe we can either fix this or make the default visualization hide the frequencies plot if it's not easy to fix?

**Comment by trvrb** [comment]
We'll be working directly from frequencies now (like https://bedford.io/talks/virus-evolution-fitness-forecasting-kitp/#/25) rather than using the ncov tree. I'm going to close this issue.
