### ISSUE TITLE
Amazon S3 authentication error

### ISSUE THREAD

**Issue by jbloom** [blab/ncov-escape#9]
I can no longer run pipeline, getting the following error:
```
botocore.exceptions.NoCredentialsError: Unable to locate credentials
```

I think this is associated with [this commit](https://github.com/blab/ncov-escape/commit/5bdea9d185dfa5167dc8e249070a3320e59f37d4) that now gets data from Amazon S3? Anyway, this may not really be a big deal if I don't need to run pipeline myself, but I'd flag it because it makes it hard for me to check code updates.

**Comment by trvrb** [comment]
We require detailed metadata with associated submission dates to properly reconstruct sequence counts that were available on past date. I've made a note of this in commit 65db26cb2b8adcb2b7590651473f3e78f929ff1e.

Once we have a more final analysis we can version the derived sequence counts.
